#!/data/data/com.termux/files/usr/bin/bash

if ! command -v adb &>/dev/null || ! command -v fastboot &>/dev/null; then
    yes | apt update && yes | apt upgrade
    echo "Installing ADB and Fastboot..."
    yes | pkg uninstall termux-adb 2>/dev/null
    curl -s https://raw.githubusercontent.com/nohajc/termux-adb/master/install.sh | bash
    ln -s $PREFIX/bin/termux-fastboot $PREFIX/bin/fastboot
    ln -s $PREFIX/bin/termux-adb $PREFIX/bin/adb
fi

if ! command -v python3 &>/dev/null; then
    echo "Installing Python3..."
    yes | pkg install python3
fi

if ! python3 -c "import Cryptodome" &>/dev/null; then
    echo "Installing Cryptodome..."
    yes | pip install pycryptodomex
fi

if ! python3 -c "import urllib3" &>/dev/null; then
    echo "Installing urllib3..."
    yes | pip install urllib3
fi

if ! python3 -c "import requests" &>/dev/null; then
    echo "Installing requests..."
    yes | pip install requests
fi

echo -e "\033[32mupdate MiUnlockTool...\033[0m"
curl "https://raw.githubusercontent.com/offici5l/MiUnlockTool/master/MiUnlockTool.py" -o "$PREFIX/bin/miunlock" && chmod +x "$PREFIX/bin/miunlock"

printf "use command: \e[1;32mmiunlock\e[0m\n"